version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    command: "go run main.go"
    depends_on:
      - db
    env_file:
      - .env
      - ./docker/env/.local.env
    ports:
      - 8080:8080
    volumes:
      - ./api:/app
  db:
    image: amazon/dynamodb-local:latest
    ports:
      - 8000:8000
    volumes:
      - db-data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"

volumes:
  db-data:
