version: '3'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - .env
      - ./docker/env/.prod.env
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      TZ: Asia/Tokyo
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ["go", "run", "main.go"]
    depends_on:
      - db
    env_file:
      - .env
      - ./docker/env/.prod.env
    ports:
      - 80:8080
    volumes:
      - ./api:/app

volumes:
  db-store:
